#!/bin/bash

options="-Wall"
out="platformer"
args=("$@")
opt=${args[0]}
# All Sane Systems:
# link_flags="-lGL -lGLU -lglut"
# OSX:
link_flags="-framework OpenGL"
if [ -z $opt ]; then
    opt="normal"
fi
if [ $opt = "debug" ]; then
    options="-g -O0 -fno-inline"
    out="demo-debug"
fi

g++ -o \
        ${out} ${options} \
        src/main.cpp \
        src/math/vec2.cpp \
        src/world/player.cpp \
        src/graphics/font.cpp \
        src/graphics/texture.cpp \
        src/system/timer.cpp \
        src/system/unique.cpp \
        -I./inc\
        ${link_flags} \
        -lSDL_image \
        -lSDL_mixer \
        `sdl-config --libs` \
        `sdl-config --cflags`
